name: PHP CS Fixer
on: [push, pull_request]
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: php-cs-fixer
      - name: PHP CS Fixer
        run: php-cs-fixer fix --dry-run
